create extension if not exists pgcrypto;

create table if not exists public.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default 'Admin Soka',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text not null,
  cover_image text,
  is_published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  description text not null,
  image text,
  event_date date,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  title text,
  caption text,
  image_url text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_articles_updated_at on public.articles;
create trigger set_articles_updated_at
before update on public.articles
for each row
execute function public.set_updated_at();

drop trigger if exists set_activities_updated_at on public.activities;
create trigger set_activities_updated_at
before update on public.activities
for each row
execute function public.set_updated_at();

drop trigger if exists set_gallery_items_updated_at on public.gallery_items;
create trigger set_gallery_items_updated_at
before update on public.gallery_items
for each row
execute function public.set_updated_at();

insert into storage.buckets (id, name, public)
values ('soka-media', 'soka-media', true)
on conflict (id) do update
set public = excluded.public;

alter table public.admins enable row level security;
alter table public.articles enable row level security;
alter table public.activities enable row level security;
alter table public.gallery_items enable row level security;

drop policy if exists "admins can view own row" on public.admins;
create policy "admins can view own row"
on public.admins
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "public can read published articles" on public.articles;
create policy "public can read published articles"
on public.articles
for select
to anon, authenticated
using (
  is_published = true
  and (published_at is null or published_at <= timezone('utc', now()))
);

drop policy if exists "admins can manage articles" on public.articles;
create policy "admins can manage articles"
on public.articles
for all
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()))
with check (exists (select 1 from public.admins where user_id = auth.uid()));

drop policy if exists "public can read activities" on public.activities;
create policy "public can read activities"
on public.activities
for select
to anon, authenticated
using (true);

drop policy if exists "admins can manage activities" on public.activities;
create policy "admins can manage activities"
on public.activities
for all
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()))
with check (exists (select 1 from public.admins where user_id = auth.uid()));

drop policy if exists "public can read gallery items" on public.gallery_items;
create policy "public can read gallery items"
on public.gallery_items
for select
to anon, authenticated
using (true);

drop policy if exists "admins can manage gallery items" on public.gallery_items;
create policy "admins can manage gallery items"
on public.gallery_items
for all
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()))
with check (exists (select 1 from public.admins where user_id = auth.uid()));

drop policy if exists "public can read media bucket" on storage.objects;
create policy "public can read media bucket"
on storage.objects
for select
to public
using (bucket_id = 'soka-media');

drop policy if exists "admins can upload media" on storage.objects;
create policy "admins can upload media"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'soka-media'
  and exists (select 1 from public.admins where user_id = auth.uid())
);

drop policy if exists "admins can update media" on storage.objects;
create policy "admins can update media"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'soka-media'
  and exists (select 1 from public.admins where user_id = auth.uid())
)
with check (
  bucket_id = 'soka-media'
  and exists (select 1 from public.admins where user_id = auth.uid())
);

drop policy if exists "admins can delete media" on storage.objects;
create policy "admins can delete media"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'soka-media'
  and exists (select 1 from public.admins where user_id = auth.uid())
);

grant usage on schema public to anon, authenticated, service_role;
grant select on public.articles, public.activities, public.gallery_items to anon;
grant select on public.admins, public.articles, public.activities, public.gallery_items to authenticated;
grant insert, update, delete on public.articles, public.activities, public.gallery_items to authenticated;
grant all privileges on public.admins, public.articles, public.activities, public.gallery_items to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
